apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: default
data:
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  WALG_GS_PREFIX: "gs://finn-poc/spilo/$(SCOPE)"
  CLONE_WALG_GS_PREFIX: "gs://finn-poc/spilo/$(CLONE_SCOPE)"
