apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-restore-cluster
  namespace: default
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "11"
  clone:
    uid: "41232075-f651-11e9-ac18-42010aa60021"
    cluster: "acid-minimal-cluster"
    timestamp: "2019-10-24T13:33:00+02:00"
 
