apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-restore2-cluster
  namespace: default
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "11"
  clone:
    uid: "aa87bbfe-f4f9-11e9-8bb1-42010aa60061"
    cluster: "acid-monitoring-cluster"
    timestamp: "2019-10-22T23:00:00+02:00"
 
