apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-restore-cluster
  namespace: default
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "11"
  clone:
    uid: "0057797c-f633-11e9-97e7-42010aa60176"
    cluster: "acid-minimal-cluster"
    timestamp: "2019-10-24T10:00:00+02:00"
 
