apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-restore-cluster
  namespace: default
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "11"
  clone:
    uid: "c81cd3c6-f694-11e9-8dec-42010aa600aa"
    cluster: "acid-minimal-cluster"
    timestamp: "2019-10-25T13:33:00+02:00"
 
