apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-restored-cluster
  namespace: default
spec:
  teamId: "ACID"
  volume:
    size: 1Gi
  numberOfInstances: 1
  postgresql:
    version: "11"
  clone:
    uid: 
    cluster: "acid-minimal-cluster"
    timestamp: "2019-10-22T23:00:00+02:00"
 
