---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: default
data:
  USE_WALG: "true"
  USE_WALG_BACKUP: "true"
  USE_WALG_RESTORE: "true"
  WALG_GS_PREFIX: gs://rl-poc/spilo/$(SCOPE)
  CLONE_WALG_GS_PREFIX: gs://rl-poc/spilo/$(CLONE_SCOPE)
  WALE_BACKUP_THRESHOLD_PERCENTAGE: "100"
  PGHOST: /home/postgres/pgdata/tmp/
