apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: rl-standby-cluster
  namespace: default
spec:
  teamId: "RL"                #First part of metadata.name must match this (lowercapsing is fine)
  volume:
    size: 1Gi                 # Size of persistent volume clain
  numberOfInstances: 1
  # postgres-operator can create users, and placed random passwords in k8s secrets, see below:  
  postgresql:
    version: "12"             # Let's perform an upgrade later
    # This is where we can configure postgreSQL. Recommend not touching shared_buffers
    parameters:
      archive_timeout: "300"  # spilo defaults it to 30 minutes, which may be a tad too long

  standby:
    s3_wal_path: gs://finn-poc/testbackup
    
