apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: rl-upgraded-cluster
  namespace: default
spec:
  teamId: "RL"   #First part of name must match
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    rldemo: []
    prometheus: []
  databases:
    rldemo: rldemo
  postgresql:
    version: "12"
    parameters:
      archive_timeout: "300"  # spilo defaults it to 30 minutes, which may be a tad too long

  clone:
    cluster: rl-demo-cluster
    timestamp: 2020-09-23T23:59:00+02:00
    
