apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: rl-demo-standby
  namespace: default
spec:
  teamId: "RL"   #First part of name must match
  volume:
    size: 5Gi
  numberOfInstances: 1
  users:
    rldemo: []
  databases:
    rldemo: rldemo
  postgresql:
    version: "9.6"
    parameters:
      archive_timeout: "300"  # spilo defaults it to 30 minutes, which may be a tad too long

  standby:
    s3_wal_path: gs://rl-poc/spilo/rl-vm-pg96
    
