apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: rl-demo-cluster
  namespace: default
spec:
  teamId: "RL"                #First part of metadata.name must match this)
  volume:
    size: 1Gi                 # Size of persistent volume clain
  numberOfInstances: 2
  postgresql:
    version: "10"             # Let's perform an upgrade later
    parameters:
      unix_socket_directories: "/var/run/postgresql,/home/postgres/pgdata/tmp"
      archive_timeout: "300s"
