apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: rl-demo-restore-cluster
  namespace: default
spec:
  teamId: "RL"   #First part of name must match
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    rldemo: []
  databases:
    rldemo: rldemo
  postgresql:
    version: "11"
    parameters:
      unix_socket_directories: "/var/run/postgresql,/home/postgres/pgdata/tmp"
      archive_timeout: "300"  # spilo defaults it to 30 minutes, which may be a tad too long

  clone:
    cluster: rl-minimal-cluster
    timestamp: 2020-09-23T23:59:00+02:00
    
