---
name: Build and push docker images

on:
  push:
    branches:
      master


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build prometheus docker image for monitoring
        run: docker build -t krorvik/pg-op-exporter:latest prometheus/

      - name: Log in to docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
